#postgres参数配置
spring:
  datasource:
#    url:
    url: jdbc:postgresql://192.168.10.212/dsignal
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#端口路径配置
server:
  port: 9099
  servlet:
    context-path: /signaltest
#swagger测试配置
swagger:
  enable: true #是否开启swagger
mybatis-plus:
  type-aliases-package: com.tydic.signaltest.model
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    sql-parser-cache: true