#postgres参数配置
spring:
  datasource:
#    url:
    url: jdbc:postgresql://192.168.10.212/dsignal
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    #redis相关配置
  redis:
    host: 127.0.0.1
    database: 0 # Redis数据库索引（默认为0）
    port: 6379
    password: null
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 5000ms # 连接超时时间（毫秒）
#端口路径配置
server:
  port: 9099
  servlet:
    context-path: /signaltest
#swagger测试配置
swagger:
  enable: true #是否开启swagger
#mybatis-plus相关配置
mybatis-plus:
  type-aliases-package: com.tydic.signaltest.model
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true